backend:
  name: git-gateway

media_folder: content/assets
public_folder: ../assets

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    fields:
      - { name: path, label: Caminho }
      - { name: title, label: Título }
      - { name: description, label: Descrição }
      - { name: topic, label: Tópico }
      - { name: thumb, label: Thumb, widget: image }
      - { name: date, label: Data }
      - { name: body, label: Corpo, widget: markdown }