backend:
  name: git-gateway

media_folder: content/assets
public_folder: ../assets

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    fields:
      - { name: title, label: Título, widget: string }
      - { name: description, label: Descrição, widget: string }
      - { name: topic, label: Tópico, widget: string }
      - { name: thumb, label: Thumb, widget: image }
      - { name: date, label: Data, widget: datetime }
      - { name: body, label: Corpo, widget: markdown }